Remove duplicate fonts from font-jetbrains-mono
Homebrew/homebrew-cask-fonts pull request #3916
Opened 2021-04-22 09:47 UTC by EinJochel

- Removed font `fonts/variable/JetBrainsMono[wght].ttf`, because it is marked as a duplicate of `fonts/ttf/JetBrainsMono.ttf` (in `Font Book.app`)
- Removed font `fonts/variable/JetBrainsMono-Italic[wght].ttf`, because it is marked as a duplicate of `fonts/ttf/JetBrainsMono-Light.ttf` (in `Font Book.app`)
- Also switched from `appcast` stanza to `livecheck`

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-04-24 12:02 UTC, vitorgalvao requested changes

2021-04-24 12:02 UTC, vitorgalvao commented on Casks/font-jetbrains-mono.rb
> +    strategy :sparkle
`:gitHub_latest` *if* it’s even needed. Try it without a `livecheck` first.

2021-04-24 12:02 UTC, vitorgalvao commented on Casks/font-jetbrains-mono.rb
> -  font "fonts/variable/JetBrainsMono-Italic[wght].ttf"
These are the variable versions. Don’t remove them.

2021-04-24 12:23 UTC, EinJochel commented on Casks/font-jetbrains-mono.rb
> -  font "fonts/variable/JetBrainsMono-Italic[wght].ttf"
But those create warnings in the `Font Book.app` and issues in some other apps.

2021-04-24 15:04 UTC, vitorgalvao commented on Casks/font-jetbrains-mono.rb
> -  font "fonts/variable/JetBrainsMono-Italic[wght].ttf"
Then nobody is happy. Some people want the variable fonts, others don’t, and we can’t satisfy everyone. For now we’ve decided to go with them, so please restore them.

You can always make a tap without them.

2021-04-25 13:27 UTC, vitorgalvao commented
Thank you.

2021-04-25 13:27 UTC, vitorgalvao approved these changes

2021-04-25 13:27 UTC, merged