add "UDEV-gothic" font
Homebrew/homebrew-cask-fonts pull request #5681
Opened 2022-03-29 06:42 UTC by justforlxz

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2022-03-29 06:45 UTC, justforlxz commented
Hi, there are two questions I can't process.

1. brew style --cask

```shell
$ brew style --fix font-udev-gothic
Inspecting 2 files
.C

Offenses:

/opt/homebrew/Caskroom/font-udev-gothic/.metadata/0.0.7/20220329064348.040/Casks/font-udev-gothic.rb:1:1: C: [Corrected] Missing frozen string literal comment.
cask "font-udev-gothic" do
^
/opt/homebrew/Caskroom/font-udev-gothic/.metadata/0.0.7/20220329064348.040/Casks/font-udev-gothic.rb:2:1: C: [Corrected] Add an empty line after magic comments.
cask "font-udev-gothic" do
^

2 files inspected, 2 offenses detected, 2 offenses corrected
```

2. brew audit --new-cask

```shell
$ brew audit --new-cask font-udev-gothic
Error: Failed to load formula: font-udev-gothic
font-udev-gothic: undefined method `cask' for Formulary::FormulaNamespace71085f2efdf388a5a3643c7406e36f61:Module
Did you mean?  case
Warning: Treating font-udev-gothic as a cask.
==> Downloading https://github.com/yuru7/udev-gothic/releases/download/v0.0.7/UDEVGothic_v0.0.7.zip
Already downloaded: /Users/lxz/Library/Caches/Homebrew/downloads/8a050c45478005137b9afdc519c325cdefa5345a80678a194c1d9c460b717a82--UDEVGothic_v0.0.7.zip
audit for font-udev-gothic: failed
 - GitHub repository too new (<30 days old)
Error: 1 problem in 1 cask detected
```

2022-04-03 23:26 UTC, bevanjkay requested changes

2022-04-03 23:26 UTC, bevanjkay commented on Casks/font-udev-gothic.rb
> +  version "0.0.7"
@justforlxz Can you please bump this to the latest version`0.0.9` - the shasum will also need updating.

2022-04-03 23:26 UTC, bevanjkay commented on Casks/font-udev-gothic.rb
> +  end
@justforlxz The livecheck block can be ommitted in this instance as `livecheck` will automatically infer the `:git` strategy from the url.

2022-04-04 00:24 UTC, justforlxz commented on Casks/font-udev-gothic.rb
> +  end
hi, i have done the update, please check again, thanks!

2022-04-04 00:26 UTC, bevanjkay approved these changes

2022-04-04 00:34 UTC, merged

2022-04-04 00:36 UTC, justforlxz commented
@bevanjkay I noticed that action has the same error as mine, how can I fix it?

```
GitHub repository too new (<30 days old)
```