font-latin-modern: use https in URL
Homebrew/homebrew-cask-fonts pull request #7900
Opened 2023-07-09 21:55 UTC by i0ntempest

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2023-07-09 23:12 UTC, bevanjkay requested changes
@i0ntempest Can you please also add a `desc` stanza?

2023-07-09 23:13 UTC, i0ntempest commented
> @i0ntempest Can you please also add a `desc` stanza?

Sure but how should I describe fonts (groups)?

2023-07-10 02:42 UTC, i0ntempest commented
> @i0ntempest Can you please also add a `desc` stanza?

Descriptions added, tho not sure if they are any good.

2023-07-10 03:30 UTC, miccal commented on Casks/font-latin-modern.rb
> +  desc "The Latin Modern font family, derived from Computer Modern fonts"
```suggestion
  desc "Latin Modern font family, derived from Computer Modern fonts"
```

2023-07-10 03:30 UTC, miccal commented on Casks/font-latin-modern.rb
```suggestion

  livecheck do
    url "https://www.gust.org.pl/projects/e-foundry/latin-modern/download"
    regex(/lm(\d+(?:\.\d+)+)otf\.zip/i)
  end

```

2023-07-10 05:25 UTC, bevanjkay approved these changes

2023-07-10 05:32 UTC, merged