Add variable noto fonts
Homebrew/homebrew-cask-fonts pull request #8984
Opened 2024-01-30 07:10 UTC by sharpenedblade

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
Livecheck is throwing an error, but the version is actually up to date.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-fonts/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
It says the repo is not popular enough. This font (from the same source repo) is already packaged here as a non-variable font so I dont think this applies here. The github repo is just a download link, the actual font is much more popular.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-01-31 19:13 UTC, bevanjkay commented
Thanks for the submission @sharpenedblade. Is there any reason these versions should not be distributed as the current `font-noto-sans` etc...?

2024-01-31 23:18 UTC, sharpenedblade commented
> Thanks for the submission @sharpenedblade. Is there any reason these versions should not be used as the current `font-noto-sans` etc...?

I dont think so, but some older apps dont handle variable fonts right, and I noticed that other fonts were packaged in the same way.

2024-02-01 05:38 UTC, bevanjkay commented
If this is the current official distribution of the fonts then yes. 

In other cases it is likely because the variable fonts are packaged separately upstream, so cannot be installed from the same archive (therefore requiring a separate cask).

2024-02-01 07:43 UTC, sharpenedblade commented
> In other cases it is likely because the variable fonts are packaged separately upstream, so cannot be installed from the same archive (therefore requiring a separate cask).

Having both regular and variable fonts installed causes inconsistant rendering in a lot of apps.

2024-02-01 08:25 UTC, bevanjkay commented
According to the documentation, we prefer variable fonts over static fonts, so this should be ok, unless it causes issues in up to date applications.
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#multiple-font-formats

2024-02-01 15:53 UTC, sharpenedblade commented
> According to the documentation, we prefer variable fonts over static fonts, so this should be ok, unless it causes issues in up to date applications. https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#multiple-font-formats

I updated the PR

2024-02-14 17:48 UTC, bevanjkay commented
Tests are currently failing. But in principle I'm happy with the changes.

2024-02-15 07:51 UTC, sharpenedblade commented
> Tests are currently failing. But in principle I'm happy with the changes.

Fixed, the only error is about popularity but there is nothing I can do about that.

2024-02-15 07:58 UTC, bevanjkay requested changes

2024-02-15 07:58 UTC, bevanjkay commented on Casks/font-noto-sans-mono.rb
>    sha256 :no_check
Now that we are using a versioned `url` a checksum can be added to each cask

2024-02-15 07:58 UTC, bevanjkay commented on Casks/font-noto-sans-mono.rb
>    sha256 :no_check
Should be good to go after that change

2024-02-15 22:38 UTC, sharpenedblade commented on Casks/font-noto-sans-mono.rb
>    sha256 :no_check
I added checksums

2024-02-17 23:19 UTC, sharpenedblade commented
All tests are passing now

2024-02-18 00:22 UTC, bevanjkay requested changes

2024-02-18 00:22 UTC, bevanjkay commented on Casks/font-noto-sans-mono.rb
> +    url "https://github.com/notofonts/latin-greek-cyrillic.git"
all of these should be adjusted to

```suggestion
    url :url
```

Sorry for the back and forth @sharpenedblade

2024-02-18 00:29 UTC, sharpenedblade commented on Casks/font-noto-sans-mono.rb
> +    url "https://github.com/notofonts/latin-greek-cyrillic.git"
Fixed

2024-02-18 00:30 UTC, bevanjkay approved these changes

2024-02-18 00:31 UTC, bevanjkay commented
Thank you @sharpenedblade

2024-02-18 00:34 UTC, merged